// app/tevm-tools/components/sidebar.tsx
'use client'

import type React from 'react'

import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ChevronDown, ChevronRight, FileIcon, FileText, FolderIcon, List } from 'lucide-react'
import { useState } from 'react'

interface FileTreeItem {
	name: string
	type: 'file' | 'folder'
	children?: FileTreeItem[]
}

interface OutlineItem {
	name: string
	type: string
	line: number
}

interface SidebarProps {
	width: number
	onResize: (width: number) => void
	activeView: 'files' | 'outline'
	onChangeView: (view: 'files' | 'outline') => void
	fileTree: FileTreeItem[]
	outline: OutlineItem[]
}

export function Sidebar({ width, onResize, activeView, onChangeView, fileTree, outline }: SidebarProps) {
	const [resizing, setResizing] = useState(false)
	const [expandedFolders, setExpandedFolders] = useState<Record<string, boolean>>({
		contracts: true,
		scripts: false,
		test: false,
	})

	const handleResizeStart = (e: React.MouseEvent) => {
		e.preventDefault()
		setResizing(true)

		const startX = e.clientX
		const startWidth = width

		const handleMouseMove = (e: MouseEvent) => {
			const newWidth = Math.max(200, Math.min(400, startWidth + e.clientX - startX))
			onResize(newWidth)
		}

		const handleMouseUp = () => {
			setResizing(false)
			document.removeEventListener('mousemove', handleMouseMove)
			document.removeEventListener('mouseup', handleMouseUp)
		}

		document.addEventListener('mousemove', handleMouseMove)
		document.addEventListener('mouseup', handleMouseUp)
	}

	const toggleFolder = (folderName: string) => {
		setExpandedFolders((prev) => ({
			...prev,
			[folderName]: !prev[folderName],
		}))
	}

	const renderFileTree = (items: FileTreeItem[], path = '') => {
		return items.map((item) => {
			const itemPath = path ? `${path}/${item.name}` : item.name

			if (item.type === 'folder') {
				const isExpanded = expandedFolders[itemPath] || false

				return (
					<div key={itemPath} className="select-none">
						<div
							className="flex items-center py-1 px-2 hover:bg-highlight-line rounded cursor-pointer"
							onClick={() => toggleFolder(itemPath)}
						>
							{isExpanded ? (
								<ChevronDown className="h-4 w-4 mr-1 flex-shrink-0" />
							) : (
								<ChevronRight className="h-4 w-4 mr-1 flex-shrink-0" />
							)}
							<FolderIcon className="h-4 w-4 mr-2 text-yellow-400" />
							<span className="truncate">{item.name}</span>
						</div>

						{isExpanded && item.children && (
							<div className="pl-4 border-l border-highlight-line ml-3">{renderFileTree(item.children, itemPath)}</div>
						)}
					</div>
				)
			}
			return (
				<div key={itemPath} className="flex items-center py-1 px-2 hover:bg-highlight-line rounded cursor-pointer ml-6">
					<FileIcon className="h-4 w-4 mr-2 text-blue-400" />
					<span className="truncate">{item.name}</span>
				</div>
			)
		})
	}

	const renderOutline = (items: OutlineItem[]) => {
		return items.map((item) => {
			let icon
			switch (item.type) {
				case 'contract':
					icon = <FileText className="h-4 w-4 mr-2 text-purple-400" />
					break
				case 'function':
					icon = <span className="text-green-400 mr-2 font-mono text-xs">fn</span>
					break
				case 'event':
					icon = <span className="text-yellow-400 mr-2 font-mono text-xs">ev</span>
					break
				default:
					icon = <span className="text-blue-400 mr-2 font-mono text-xs">var</span>
			}

			return (
				<div
					key={`${item.name}-${item.line}`}
					className="flex items-center py-1 px-2 hover:bg-highlight-line rounded cursor-pointer"
				>
					{icon}
					<span className="truncate">{item.name}</span>
					<span className="ml-auto text-text-secondary text-xs">{item.line}</span>
				</div>
			)
		})
	}

	return (
		<div
			className="flex-shrink-0 bg-bg-panel border-r border-highlight-line relative"
			style={{ width: `${width}px` }}
			role="navigation"
			aria-label="Sidebar"
		>
			<Tabs value={activeView} onValueChange={(v) => onChangeView(v as 'files' | 'outline')}>
				<TabsList className="w-full">
					<TabsTrigger value="files" className="flex-1">
						<FileIcon className="h-4 w-4 mr-2" />
						Files
					</TabsTrigger>
					<TabsTrigger value="outline" className="flex-1">
						<List className="h-4 w-4 mr-2" />
						Outline
					</TabsTrigger>
				</TabsList>

				<TabsContent value="files" className="p-0 overflow-auto h-[calc(100vh-96px)]">
					<div className="p-2">{renderFileTree(fileTree)}</div>
				</TabsContent>

				<TabsContent value="outline" className="p-0 overflow-auto h-[calc(100vh-96px)]">
					<div className="p-2">{renderOutline(outline)}</div>
				</TabsContent>
			</Tabs>

			<div
				className="absolute top-0 right-0 w-2 h-full cursor-col-resize hover:bg-highlight-line"
				onMouseDown={handleResizeStart}
				role="separator"
				aria-orientation="vertical"
				aria-label="Resize sidebar"
			/>
		</div>
	)
}

// app/src/components/Sidebar.svelte
<script>
  import { onMount } from 'svelte';
  
  // Props
  export let width = 250; // Default width
  export let minWidth = 180;
  export let maxWidth = 400;
  export let onWidthChange = (width) => {}; // Callback for width changes
  
  // State
  let activeView = 'files'; // 'files' or 'outline'
  let isResizing = false;
  let sidebarElement;
  
  // Mock data for file tree
  const fileTree = [
    { id: 'contracts', name: 'contracts', type: 'folder', expanded: true, children: [
      { id: 'contracts/Token.sol', name: 'Token.sol', type: 'file', active: true },
      { id: 'contracts/Vault.sol', name: 'Vault.sol', type: 'file' },
    ]},
    { id: 'scripts', name: 'scripts', type: 'folder', expanded: false, children: [
      { id: 'scripts/deploy.ts', name: 'deploy.ts', type: 'file' },
    ]},
    { id: 'test', name: 'test', type: 'folder', expanded: false, children: [
      { id: 'test/Token.test.ts', name: 'Token.test.ts', type: 'file' },
    ]},
    { id: 'README.md', name: 'README.md', type: 'file' },
  ];
  
  // Mock data for contract outline
  const outline = [
    { id: 'contract-Token', name: 'Token', type: 'contract', line: 5 },
    { id: 'state-balances', name: 'balances', type: 'state', line: 6 },
    { id: 'state-totalSupply', name: 'totalSupply', type: 'state', line: 7 },
    { id: 'event-Transfer', name: 'Transfer', type: 'event', line: 9 },
    { id: 'function-balanceOf', name: 'balanceOf', type: 'function', line: 11 },
    { id: 'function-transfer', name: 'transfer', type: 'function', line: 15 },
    { id: 'function-_transfer', name: 'transfer (internal)', type: 'function', line: 22 },
  ];
  
  // Event handlers
  function switchView(view) {
    activeView = view;
  }
  
  function startResize(event) {
    isResizing = true;
    
    const startX = event.clientX;
    const startWidth = width;
    
    function handleMouseMove(e) {
      const deltaX = e.clientX - startX;
      const newWidth = Math.max(minWidth, Math.min(maxWidth, startWidth + deltaX));
      width = newWidth;
      onWidthChange(newWidth);
    }
    
    function handleMouseUp() {
      isResizing = false;
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    }
    
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
  }
  
  function toggleFolder(folder) {
    folder.expanded = !folder.expanded;
  }
  
  function selectFile(file) {
    // Reset all active states
    function resetActive(items) {
      items.forEach(item => {
        item.active = false;
        if (item.children) resetActive(item.children);
      });
    }
    
    resetActive(fileTree);
    file.active = true;
  }
  
  function jumpToLine(item) {
    console.log(`Jump to line ${item.line}: ${item.name}`);
    // Implement line navigation logic
  }
  
  // Lifecycle
  onMount(() => {
    // Any initialization if needed
  });
</script>

<aside 
  class="sidebar {isResizing ? 'resizing' : ''}" 
  style="width: {width}px;" 
  bind:this={sidebarElement}
>
  <div class="tabs">
    <button 
      class="tab-button {activeView === 'files' ? 'active' : ''}" 
      on:click={() => switchView('files')}
      title="Files"
      aria-label="Switch to file explorer"
    >
      <span class="icon">📁</span>
    </button>
    <button 
      class="tab-button {activeView === 'outline' ? 'active' : ''}" 
      on:click={() => switchView('outline')}
      title="Outline"
      aria-label="Switch to code outline"
    >
      <span class="icon">📋</span>
    </button>
  </div>
  
  <div class="sidebar-content">
    {#if activeView === 'files'}
      <div class="file-explorer">
        <div class="heading">
          <h3>Explorer</h3>
        </div>
        <div class="tree-view">
          {#each fileTree as item}
            {#if item.type === 'folder'}
              <div class="folder">
                <div 
                  class="folder-header"
                  on:click={() => toggleFolder(item)}
                >
                  <span class="icon">{item.expanded ? '📂' : '📁'}</span>
                  <span class="folder-name">{item.name}</span>
                </div>
                
                {#if item.expanded && item.children}
                  <div class="folder-children">
                    {#each item.children as child}
                      {#if child.type === 'file'}
                        <div 
                          class="file {child.active ? 'active' : ''}"
                          on:click={() => selectFile(child)}
                        >
                          <span class="icon">📄</span>
                          <span class="file-name">{child.name}</span>
                        </div>
                      {/if}
                    {/each}
                  </div>
                {/if}
              </div>
            {:else if item.type === 'file'}
              <div 
                class="file {item.active ? 'active' : ''}"
                on:click={() => selectFile(item)}  
              >
                <span class="icon">📄</span>
                <span class="file-name">{item.name}</span>
              </div>
            {/if}
          {/each}
        </div>
      </div>
    {:else if activeView === 'outline'}
      <div class="outline-view">
        <div class="heading">
          <h3>Outline</h3>
        </div>
        <div class="outline-list">
          {#each outline as item}
            <div 
              class="outline-item" 
              on:click={() => jumpToLine(item)}
            >
              <span class="icon">
                {#if item.type === 'contract'}
                  📘
                {:else if item.type === 'function'}
                  🔧
                {:else if item.type === 'event'}
                  🔔
                {:else if item.type === 'state'}
                  💾
                {:else}
                  📄
                {/if}
              </span>
              <span class="outline-name">{item.name}</span>
              <span class="outline-line">{item.line}</span>
            </div>
          {/each}
        </div>
      </div>
    {/if}
  </div>
  
  <div 
    class="resize-handle"
    on:mousedown={startResize}
    aria-label="Resize sidebar"
    role="separator"
    aria-orientation="vertical"
  ></div>
</aside>

<style>
  .sidebar {
    position: fixed;
    left: 0;
    top: var(--header-height);
    height: calc(100vh - var(--header-height));
    background-color: var(--bg-panel);
    border-right: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    flex-direction: column;
    overflow: hidden;
    z-index: 10;
  }
  
  .sidebar.resizing {
    user-select: none;
    pointer-events: none;
  }
  
  .tabs {
    display: flex;
    padding: var(--space-1);
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  }
  
  .tab-button {
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    color: var(--text-secondary);
    border: none;
    border-radius: 4px;
    width: 32px;
    height: 32px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.2s, color 0.2s;
  }
  
  .tab-button.active {
    color: var(--text-primary);
    background-color: var(--highlight-line);
  }
  
  .tab-button:hover {
    background-color: var(--highlight-line);
  }
  
  .sidebar-content {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
  }
  
  .heading {
    padding: var(--space-1);
    margin-bottom: var(--space-1);
  }
  
  .heading h3 {
    font-size: 14px;
    font-weight: var(--font-weight-bold);
    margin: 0;
    color: var(--text-secondary);
  }
  
  .tree-view {
    display: flex;
    flex-direction: column;
  }
  
  .folder, .file {
    display: flex;
    flex-direction: column;
  }
  
  .folder-header, .file {
    display: flex;
    align-items: center;
    padding: 4px var(--space-1);
    cursor: pointer;
    border-radius: 4px;
    margin: 1px var(--space-1);
    transition: background-color 0.2s;
  }
  
  .folder-header:hover, .file:hover {
    background-color: var(--highlight-line);
  }
  
  .file.active {
    background-color: var(--highlight-line);
    color: var(--accent);
  }
  
  .folder-children {
    margin-left: var(--space-3);
  }
  
  .icon {
    margin-right: var(--space-1);
    display: flex;
    align-items: center;
  }
  
  .folder-name, .file-name {
    flex: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  
  .outline-list {
    display: flex;
    flex-direction: column;
  }
  
  .outline-item {
    display: flex;
    align-items: center;
    padding: 4px var(--space-1);
    cursor: pointer;
    border-radius: 4px;
    margin: 1px var(--space-1);
    transition: background-color 0.2s;
  }
  
  .outline-item:hover {
    background-color: var(--highlight-line);
  }
  
  .outline-name {
    flex: 1;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  
  .outline-line {
    color: var(--text-secondary);
    font-size: 12px;
    margin-left: var(--space-1);
  }
  
  .resize-handle {
    position: absolute;
    top: 0;
    right: -3px;
    width: 6px;
    height: 100%;
    cursor: col-resize;
    z-index: 10;
  }
  
  .resize-handle:hover {
    background-color: rgba(124, 58, 237, 0.3);
  }
  
  @media (max-width: 600px) {
    .sidebar {
      transform: translateX(-100%);
      transition: transform 0.3s ease;
    }
    
    .sidebar.open {
      transform: translateX(0);
    }
  }
</style>
